name: Build iOS Tweak

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    env:
      THEOS: ${{ runner.home }}/theos
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install Theos
      run: git clone --depth=1 https://github.com/theos/theos.git $THEOS
    
    - name: Update Theos
      run: $THEOS/bin/update-theos
    
    - name: Install iOS SDK
      run: $THEOS/bin/install-sdk latest
    
    - name: Build Tweak
      run: |
        cd "ARIYAN_IOS"
        make clean package
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: FF-Package
        path: "ARIYAN_IOS/packages/"
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ARIYAN_IOS/packages/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
