name: Build iOS Tweak

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build Tweak
      run: |
        set -x
        export THEOS=$(pwd)/theos
        git clone --depth=1 https://github.com/theos/theos.git $THEOS
        $THEOS/bin/update-theos
        $THEOS/bin/install-sdk latest
        cd ARIYAN_IOS
        make clean package
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-output
        path: ARIYAN_IOS/packages/

